# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env
        run: |
          touch /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'DATABASE_URL=${{secrets.DATABASE_URL}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'CLOUDINARY_URL=${{secrets.CLOUDINARY_URL}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'GOOGLE_REFRESH_TOKEN=${{secrets.GOOGLE_REFRESH_TOKEN}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
          echo 'GOOGLE_REDIRECT_URI=${{secrets.GOOGLE_REDIRECT_URI}}' >> /home/mokletdev/actions-runner/_work/antareja/antareja/.env.local
      - name: Install Modules
        run: npm ci
      - name: Generate prisma schema
        run: npm run prisma:generate
      - name: Build site
        run: npm run build --if-present
      - name: change dir
        run: cd /home/mokletdev/actions-runner/_work/antareja/antareja
      - run: pm2 restart 0
